import { SuitsOptionsSectionResponsive } from "./SuitsOptionsSectionResponsive";
import { ISecaoOpcoesTrajes } from "@/services/interfaces";

export interface ISuitsOptionsSectionProps {}

export const SuitsOptionsSection = async (props: ISuitsOptionsSectionProps) => {
  return <SuitsOptionsSectionResponsive data={data} />;
};

const data: ISecaoOpcoesTrajes = {
  id: 1,
  attributes: {
    Titulo: "Confira as sugestões da Suits para você:",
    TextoBotao: "QUERO PROVAR",
    createdAt: "2024-09-27T12:50:41.086Z",
    updatedAt: "2024-09-27T13:27:16.623Z",
    OpcaoTraje: [
      {
        id: 1,
        Titulo: "Casamento Noturno",
        Descricao: [
          {
            type: "paragraph",
            children: [
              {
                text: "Para casamentos noturnos, opte por um terno escuro e formal, como preto ou azul-marinho, com gravata discreta e sapatos polidos.",
                type: "text",
              },
            ],
          },
        ],
        Fotos: {
          data: [
            {
              id: 8,
              attributes: {
                name: "casamento not2.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/large_casamento_not2_ee8a546900.jpg",
                    hash: "large_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "large_casamento not2.jpeg",
                    path: null,
                    size: 35.59,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 35592,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/small_casamento_not2_ee8a546900.jpg",
                    hash: "small_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "small_casamento not2.jpeg",
                    path: null,
                    size: 12.46,
                    width: 333,
                    height: 500,
                    sizeInBytes: 12459,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/medium_casamento_not2_ee8a546900.jpg",
                    hash: "medium_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "medium_casamento not2.jpeg",
                    path: null,
                    size: 22.58,
                    width: 500,
                    height: 750,
                    sizeInBytes: 22581,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/thumbnail_casamento_not2_ee8a546900.jpg",
                    hash: "thumbnail_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento not2.jpeg",
                    path: null,
                    size: 2.69,
                    width: 104,
                    height: 156,
                    sizeInBytes: 2685,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_not2_ee8a546900",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 278.42,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/casamento_not2_ee8a546900.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_not2_ee8a546900",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:23:07.656Z",
                updatedAt: "2024-09-27T13:23:07.656Z",
              },
            },
            {
              id: 9,
              attributes: {
                name: "casamento not3.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/large_casamento_not3_85a746a756.jpg",
                    hash: "large_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "large_casamento not3.jpeg",
                    path: null,
                    size: 56.63,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 56634,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/small_casamento_not3_85a746a756.jpg",
                    hash: "small_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "small_casamento not3.jpeg",
                    path: null,
                    size: 17.1,
                    width: 333,
                    height: 500,
                    sizeInBytes: 17104,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/medium_casamento_not3_85a746a756.jpg",
                    hash: "medium_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "medium_casamento not3.jpeg",
                    path: null,
                    size: 33.41,
                    width: 500,
                    height: 750,
                    sizeInBytes: 33407,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/thumbnail_casamento_not3_85a746a756.jpg",
                    hash: "thumbnail_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento not3.jpeg",
                    path: null,
                    size: 3.22,
                    width: 104,
                    height: 156,
                    sizeInBytes: 3216,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_not3_85a746a756",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 592.81,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/casamento_not3_85a746a756.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_not3_85a746a756",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:23:08.048Z",
                updatedAt: "2024-09-27T13:23:08.048Z",
              },
            },
            {
              id: 10,
              attributes: {
                name: "casamento not1.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/large_casamento_not1_37c2fe1fbc.jpg",
                    hash: "large_casamento_not1_37c2fe1fbc",
                    mime: "image/jpeg",
                    name: "large_casamento not1.jpeg",
                    path: null,
                    size: 59.12,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 59115,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_not1_37c2fe1fbc",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/small_casamento_not1_37c2fe1fbc.jpg",
                    hash: "small_casamento_not1_37c2fe1fbc",
                    mime: "image/jpeg",
                    name: "small_casamento not1.jpeg",
                    path: null,
                    size: 18.58,
                    width: 333,
                    height: 500,
                    sizeInBytes: 18584,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_not1_37c2fe1fbc",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/medium_casamento_not1_37c2fe1fbc.jpg",
                    hash: "medium_casamento_not1_37c2fe1fbc",
                    mime: "image/jpeg",
                    name: "medium_casamento not1.jpeg",
                    path: null,
                    size: 35.83,
                    width: 500,
                    height: 750,
                    sizeInBytes: 35833,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_not1_37c2fe1fbc",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/thumbnail_casamento_not1_37c2fe1fbc.jpg",
                    hash: "thumbnail_casamento_not1_37c2fe1fbc",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento not1.jpeg",
                    path: null,
                    size: 3.44,
                    width: 104,
                    height: 156,
                    sizeInBytes: 3439,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_not1_37c2fe1fbc",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_not1_37c2fe1fbc",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 550.46,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/casamento_not1_37c2fe1fbc.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_not1_37c2fe1fbc",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:23:08.092Z",
                updatedAt: "2024-09-27T13:23:08.092Z",
              },
            },
          ],
        },
      },
      {
        id: 4,
        Titulo: "Casamento Diurno",
        Descricao: [
          {
            type: "paragraph",
            children: [
              {
                text: "Casamentos diurnos pedem ternos claros, como bege ou cinza. Tecidos leves, gravatas suaves e sapatos marrons completam o look.",
                type: "text",
              },
            ],
          },
        ],
        Fotos: {
          data: [
            {
              id: 7,
              attributes: {
                name: "casamento diu1.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/large_casamento_diu1_6935ea0ad0.jpg",
                    hash: "large_casamento_diu1_6935ea0ad0",
                    mime: "image/jpeg",
                    name: "large_casamento diu1.jpeg",
                    path: null,
                    size: 29.08,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 29077,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_diu1_6935ea0ad0",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/small_casamento_diu1_6935ea0ad0.jpg",
                    hash: "small_casamento_diu1_6935ea0ad0",
                    mime: "image/jpeg",
                    name: "small_casamento diu1.jpeg",
                    path: null,
                    size: 10.14,
                    width: 333,
                    height: 500,
                    sizeInBytes: 10142,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_diu1_6935ea0ad0",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/medium_casamento_diu1_6935ea0ad0.jpg",
                    hash: "medium_casamento_diu1_6935ea0ad0",
                    mime: "image/jpeg",
                    name: "medium_casamento diu1.jpeg",
                    path: null,
                    size: 18.61,
                    width: 500,
                    height: 750,
                    sizeInBytes: 18612,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_diu1_6935ea0ad0",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/thumbnail_casamento_diu1_6935ea0ad0.jpg",
                    hash: "thumbnail_casamento_diu1_6935ea0ad0",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento diu1.jpeg",
                    path: null,
                    size: 1.96,
                    width: 104,
                    height: 156,
                    sizeInBytes: 1961,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_diu1_6935ea0ad0",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_diu1_6935ea0ad0",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 232.58,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/casamento_diu1_6935ea0ad0.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_diu1_6935ea0ad0",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:20:36.343Z",
                updatedAt: "2024-09-27T13:20:36.343Z",
              },
            },
            {
              id: 6,
              attributes: {
                name: "casamento diu2.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/large_casamento_diu2_caefa2bd9a.jpg",
                    hash: "large_casamento_diu2_caefa2bd9a",
                    mime: "image/jpeg",
                    name: "large_casamento diu2.jpeg",
                    path: null,
                    size: 37.75,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 37752,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_diu2_caefa2bd9a",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/small_casamento_diu2_caefa2bd9a.jpg",
                    hash: "small_casamento_diu2_caefa2bd9a",
                    mime: "image/jpeg",
                    name: "small_casamento diu2.jpeg",
                    path: null,
                    size: 13.34,
                    width: 333,
                    height: 500,
                    sizeInBytes: 13337,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_diu2_caefa2bd9a",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/medium_casamento_diu2_caefa2bd9a.jpg",
                    hash: "medium_casamento_diu2_caefa2bd9a",
                    mime: "image/jpeg",
                    name: "medium_casamento diu2.jpeg",
                    path: null,
                    size: 24.13,
                    width: 500,
                    height: 750,
                    sizeInBytes: 24126,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_diu2_caefa2bd9a",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/thumbnail_casamento_diu2_caefa2bd9a.jpg",
                    hash: "thumbnail_casamento_diu2_caefa2bd9a",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento diu2.jpeg",
                    path: null,
                    size: 2.63,
                    width: 104,
                    height: 156,
                    sizeInBytes: 2633,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_diu2_caefa2bd9a",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_diu2_caefa2bd9a",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 291.08,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/casamento_diu2_caefa2bd9a.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_diu2_caefa2bd9a",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:20:36.282Z",
                updatedAt: "2024-09-27T13:20:36.282Z",
              },
            },
            {
              id: 5,
              attributes: {
                name: "casamento diu3.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/large_casamento_diu3_95c9e155f8.jpg",
                    hash: "large_casamento_diu3_95c9e155f8",
                    mime: "image/jpeg",
                    name: "large_casamento diu3.jpeg",
                    path: null,
                    size: 41.31,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 41314,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_diu3_95c9e155f8",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/small_casamento_diu3_95c9e155f8.jpg",
                    hash: "small_casamento_diu3_95c9e155f8",
                    mime: "image/jpeg",
                    name: "small_casamento diu3.jpeg",
                    path: null,
                    size: 13.55,
                    width: 333,
                    height: 500,
                    sizeInBytes: 13554,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_diu3_95c9e155f8",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/medium_casamento_diu3_95c9e155f8.jpg",
                    hash: "medium_casamento_diu3_95c9e155f8",
                    mime: "image/jpeg",
                    name: "medium_casamento diu3.jpeg",
                    path: null,
                    size: 25.64,
                    width: 500,
                    height: 750,
                    sizeInBytes: 25644,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_diu3_95c9e155f8",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/thumbnail_casamento_diu3_95c9e155f8.jpg",
                    hash: "thumbnail_casamento_diu3_95c9e155f8",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento diu3.jpeg",
                    path: null,
                    size: 2.55,
                    width: 104,
                    height: 156,
                    sizeInBytes: 2550,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_diu3_95c9e155f8",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_diu3_95c9e155f8",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 386.9,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443235/Suits/casamento_diu3_95c9e155f8.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_diu3_95c9e155f8",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:20:35.990Z",
                updatedAt: "2024-09-27T13:20:35.990Z",
              },
            },
          ],
        },
      },
      {
        id: 3,
        Titulo: "Formatura Noturna",
        Descricao: [
          {
            type: "paragraph",
            children: [
              {
                text: "Em formaturas noturnas, prefira um terno preto ou azul escuro. Gravatas elegantes e sapatos de couro garantem sofisticação.",
                type: "text",
              },
            ],
          },
        ],
        Fotos: {
          data: [
            {
              id: 11,
              attributes: {
                name: "2H0A9939.jpeg",
                alternativeText: null,
                caption: null,
                width: 3000,
                height: 2000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/large_2_H0_A9939_53d63ee139.jpg",
                    hash: "large_2_H0_A9939_53d63ee139",
                    mime: "image/jpeg",
                    name: "large_2H0A9939.jpeg",
                    path: null,
                    size: 71.87,
                    width: 1000,
                    height: 667,
                    sizeInBytes: 71869,
                    provider_metadata: {
                      public_id: "Suits/large_2_H0_A9939_53d63ee139",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/small_2_H0_A9939_53d63ee139.jpg",
                    hash: "small_2_H0_A9939_53d63ee139",
                    mime: "image/jpeg",
                    name: "small_2H0A9939.jpeg",
                    path: null,
                    size: 24.31,
                    width: 500,
                    height: 333,
                    sizeInBytes: 24311,
                    provider_metadata: {
                      public_id: "Suits/small_2_H0_A9939_53d63ee139",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/medium_2_H0_A9939_53d63ee139.jpg",
                    hash: "medium_2_H0_A9939_53d63ee139",
                    mime: "image/jpeg",
                    name: "medium_2H0A9939.jpeg",
                    path: null,
                    size: 45.88,
                    width: 750,
                    height: 500,
                    sizeInBytes: 45883,
                    provider_metadata: {
                      public_id: "Suits/medium_2_H0_A9939_53d63ee139",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/thumbnail_2_H0_A9939_53d63ee139.jpg",
                    hash: "thumbnail_2_H0_A9939_53d63ee139",
                    mime: "image/jpeg",
                    name: "thumbnail_2H0A9939.jpeg",
                    path: null,
                    size: 7.67,
                    width: 234,
                    height: 156,
                    sizeInBytes: 7669,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_2_H0_A9939_53d63ee139",
                      resource_type: "image",
                    },
                  },
                },
                hash: "2_H0_A9939_53d63ee139",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 502.16,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/2_H0_A9939_53d63ee139.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/2_H0_A9939_53d63ee139",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:24:05.275Z",
                updatedAt: "2024-09-27T13:24:05.275Z",
              },
            },
            {
              id: 12,
              attributes: {
                name: "festa de gala 2.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/large_festa_de_gala_2_00768ec9e9.jpg",
                    hash: "large_festa_de_gala_2_00768ec9e9",
                    mime: "image/jpeg",
                    name: "large_festa de gala 2.jpeg",
                    path: null,
                    size: 55.26,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 55263,
                    provider_metadata: {
                      public_id: "Suits/large_festa_de_gala_2_00768ec9e9",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/small_festa_de_gala_2_00768ec9e9.jpg",
                    hash: "small_festa_de_gala_2_00768ec9e9",
                    mime: "image/jpeg",
                    name: "small_festa de gala 2.jpeg",
                    path: null,
                    size: 18.94,
                    width: 333,
                    height: 500,
                    sizeInBytes: 18942,
                    provider_metadata: {
                      public_id: "Suits/small_festa_de_gala_2_00768ec9e9",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/medium_festa_de_gala_2_00768ec9e9.jpg",
                    hash: "medium_festa_de_gala_2_00768ec9e9",
                    mime: "image/jpeg",
                    name: "medium_festa de gala 2.jpeg",
                    path: null,
                    size: 35.03,
                    width: 500,
                    height: 750,
                    sizeInBytes: 35035,
                    provider_metadata: {
                      public_id: "Suits/medium_festa_de_gala_2_00768ec9e9",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/thumbnail_festa_de_gala_2_00768ec9e9.jpg",
                    hash: "thumbnail_festa_de_gala_2_00768ec9e9",
                    mime: "image/jpeg",
                    name: "thumbnail_festa de gala 2.jpeg",
                    path: null,
                    size: 3.62,
                    width: 104,
                    height: 156,
                    sizeInBytes: 3618,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_festa_de_gala_2_00768ec9e9",
                      resource_type: "image",
                    },
                  },
                },
                hash: "festa_de_gala_2_00768ec9e9",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 468.18,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443444/Suits/festa_de_gala_2_00768ec9e9.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/festa_de_gala_2_00768ec9e9",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:24:05.395Z",
                updatedAt: "2024-09-27T13:24:05.395Z",
              },
            },
            {
              id: 9,
              attributes: {
                name: "casamento not3.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/large_casamento_not3_85a746a756.jpg",
                    hash: "large_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "large_casamento not3.jpeg",
                    path: null,
                    size: 56.63,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 56634,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/small_casamento_not3_85a746a756.jpg",
                    hash: "small_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "small_casamento not3.jpeg",
                    path: null,
                    size: 17.1,
                    width: 333,
                    height: 500,
                    sizeInBytes: 17104,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/medium_casamento_not3_85a746a756.jpg",
                    hash: "medium_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "medium_casamento not3.jpeg",
                    path: null,
                    size: 33.41,
                    width: 500,
                    height: 750,
                    sizeInBytes: 33407,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/thumbnail_casamento_not3_85a746a756.jpg",
                    hash: "thumbnail_casamento_not3_85a746a756",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento not3.jpeg",
                    path: null,
                    size: 3.22,
                    width: 104,
                    height: 156,
                    sizeInBytes: 3216,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_not3_85a746a756",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_not3_85a746a756",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 592.81,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/casamento_not3_85a746a756.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_not3_85a746a756",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:23:08.048Z",
                updatedAt: "2024-09-27T13:23:08.048Z",
              },
            },
          ],
        },
      },
      {
        id: 2,
        Titulo: "Evento Corporativo",
        Descricao: [
          {
            type: "paragraph",
            children: [
              {
                text: "Para eventos corporativos, use um terno em tons de cinza ou azul, com camisa clara e gravata discreta para um visual profissional.",
                type: "text",
              },
            ],
          },
        ],
        Fotos: {
          data: [
            {
              id: 13,
              attributes: {
                name: "corp2.jpeg",
                alternativeText: null,
                caption: null,
                width: 3000,
                height: 2000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443536/Suits/large_corp2_573a7be278.jpg",
                    hash: "large_corp2_573a7be278",
                    mime: "image/jpeg",
                    name: "large_corp2.jpeg",
                    path: null,
                    size: 68.08,
                    width: 1000,
                    height: 667,
                    sizeInBytes: 68081,
                    provider_metadata: {
                      public_id: "Suits/large_corp2_573a7be278",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443536/Suits/small_corp2_573a7be278.jpg",
                    hash: "small_corp2_573a7be278",
                    mime: "image/jpeg",
                    name: "small_corp2.jpeg",
                    path: null,
                    size: 24.28,
                    width: 500,
                    height: 333,
                    sizeInBytes: 24276,
                    provider_metadata: {
                      public_id: "Suits/small_corp2_573a7be278",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443536/Suits/medium_corp2_573a7be278.jpg",
                    hash: "medium_corp2_573a7be278",
                    mime: "image/jpeg",
                    name: "medium_corp2.jpeg",
                    path: null,
                    size: 44.35,
                    width: 750,
                    height: 500,
                    sizeInBytes: 44351,
                    provider_metadata: {
                      public_id: "Suits/medium_corp2_573a7be278",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443536/Suits/thumbnail_corp2_573a7be278.jpg",
                    hash: "thumbnail_corp2_573a7be278",
                    mime: "image/jpeg",
                    name: "thumbnail_corp2.jpeg",
                    path: null,
                    size: 7.91,
                    width: 234,
                    height: 156,
                    sizeInBytes: 7913,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_corp2_573a7be278",
                      resource_type: "image",
                    },
                  },
                },
                hash: "corp2_573a7be278",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 451.01,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443536/Suits/corp2_573a7be278.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/corp2_573a7be278",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:25:37.191Z",
                updatedAt: "2024-09-27T13:25:37.191Z",
              },
            },
            {
              id: 14,
              attributes: {
                name: "corp4.jpeg",
                alternativeText: null,
                caption: null,
                width: 3000,
                height: 2000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443538/Suits/large_corp4_9536196efb.jpg",
                    hash: "large_corp4_9536196efb",
                    mime: "image/jpeg",
                    name: "large_corp4.jpeg",
                    path: null,
                    size: 71.87,
                    width: 1000,
                    height: 667,
                    sizeInBytes: 71869,
                    provider_metadata: {
                      public_id: "Suits/large_corp4_9536196efb",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443538/Suits/small_corp4_9536196efb.jpg",
                    hash: "small_corp4_9536196efb",
                    mime: "image/jpeg",
                    name: "small_corp4.jpeg",
                    path: null,
                    size: 24.31,
                    width: 500,
                    height: 333,
                    sizeInBytes: 24311,
                    provider_metadata: {
                      public_id: "Suits/small_corp4_9536196efb",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443538/Suits/medium_corp4_9536196efb.jpg",
                    hash: "medium_corp4_9536196efb",
                    mime: "image/jpeg",
                    name: "medium_corp4.jpeg",
                    path: null,
                    size: 45.88,
                    width: 750,
                    height: 500,
                    sizeInBytes: 45883,
                    provider_metadata: {
                      public_id: "Suits/medium_corp4_9536196efb",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443538/Suits/thumbnail_corp4_9536196efb.jpg",
                    hash: "thumbnail_corp4_9536196efb",
                    mime: "image/jpeg",
                    name: "thumbnail_corp4.jpeg",
                    path: null,
                    size: 7.67,
                    width: 234,
                    height: 156,
                    sizeInBytes: 7669,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_corp4_9536196efb",
                      resource_type: "image",
                    },
                  },
                },
                hash: "corp4_9536196efb",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 502.16,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443538/Suits/corp4_9536196efb.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/corp4_9536196efb",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:25:39.203Z",
                updatedAt: "2024-09-27T13:25:39.203Z",
              },
            },
            {
              id: 15,
              attributes: {
                name: "corp3.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443539/Suits/large_corp3_a60d6884c5.jpg",
                    hash: "large_corp3_a60d6884c5",
                    mime: "image/jpeg",
                    name: "large_corp3.jpeg",
                    path: null,
                    size: 114.32,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 114324,
                    provider_metadata: {
                      public_id: "Suits/large_corp3_a60d6884c5",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443539/Suits/small_corp3_a60d6884c5.jpg",
                    hash: "small_corp3_a60d6884c5",
                    mime: "image/jpeg",
                    name: "small_corp3.jpeg",
                    path: null,
                    size: 34.51,
                    width: 333,
                    height: 500,
                    sizeInBytes: 34514,
                    provider_metadata: {
                      public_id: "Suits/small_corp3_a60d6884c5",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443539/Suits/medium_corp3_a60d6884c5.jpg",
                    hash: "medium_corp3_a60d6884c5",
                    mime: "image/jpeg",
                    name: "medium_corp3.jpeg",
                    path: null,
                    size: 70.16,
                    width: 500,
                    height: 750,
                    sizeInBytes: 70164,
                    provider_metadata: {
                      public_id: "Suits/medium_corp3_a60d6884c5",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443539/Suits/thumbnail_corp3_a60d6884c5.jpg",
                    hash: "thumbnail_corp3_a60d6884c5",
                    mime: "image/jpeg",
                    name: "thumbnail_corp3.jpeg",
                    path: null,
                    size: 4.98,
                    width: 104,
                    height: 156,
                    sizeInBytes: 4981,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_corp3_a60d6884c5",
                      resource_type: "image",
                    },
                  },
                },
                hash: "corp3_a60d6884c5",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 762.17,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443539/Suits/corp3_a60d6884c5.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/corp3_a60d6884c5",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:25:39.912Z",
                updatedAt: "2024-09-27T13:25:39.912Z",
              },
            },
          ],
        },
      },
      {
        id: 5,
        Titulo: "Festa de Gala",
        Descricao: [
          {
            type: "paragraph",
            children: [
              {
                text: "Numa festa de gala, escolha um smoking preto clássico, com laço, camisa branca e sapatos de verniz para máxima elegância.",
                type: "text",
              },
            ],
          },
        ],
        Fotos: {
          data: [
            {
              id: 16,
              attributes: {
                name: "2H0A1377-2.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/large_2_H0_A1377_2_797befb0a5.jpg",
                    hash: "large_2_H0_A1377_2_797befb0a5",
                    mime: "image/jpeg",
                    name: "large_2H0A1377-2.jpeg",
                    path: null,
                    size: 42.29,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 42289,
                    provider_metadata: {
                      public_id: "Suits/large_2_H0_A1377_2_797befb0a5",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/small_2_H0_A1377_2_797befb0a5.jpg",
                    hash: "small_2_H0_A1377_2_797befb0a5",
                    mime: "image/jpeg",
                    name: "small_2H0A1377-2.jpeg",
                    path: null,
                    size: 14.53,
                    width: 333,
                    height: 500,
                    sizeInBytes: 14530,
                    provider_metadata: {
                      public_id: "Suits/small_2_H0_A1377_2_797befb0a5",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/medium_2_H0_A1377_2_797befb0a5.jpg",
                    hash: "medium_2_H0_A1377_2_797befb0a5",
                    mime: "image/jpeg",
                    name: "medium_2H0A1377-2.jpeg",
                    path: null,
                    size: 26.68,
                    width: 500,
                    height: 750,
                    sizeInBytes: 26681,
                    provider_metadata: {
                      public_id: "Suits/medium_2_H0_A1377_2_797befb0a5",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/thumbnail_2_H0_A1377_2_797befb0a5.jpg",
                    hash: "thumbnail_2_H0_A1377_2_797befb0a5",
                    mime: "image/jpeg",
                    name: "thumbnail_2H0A1377-2.jpeg",
                    path: null,
                    size: 2.83,
                    width: 104,
                    height: 156,
                    sizeInBytes: 2828,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_2_H0_A1377_2_797befb0a5",
                      resource_type: "image",
                    },
                  },
                },
                hash: "2_H0_A1377_2_797befb0a5",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 397.93,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/2_H0_A1377_2_797befb0a5.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/2_H0_A1377_2_797befb0a5",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:26:22.142Z",
                updatedAt: "2024-09-27T13:26:22.142Z",
              },
            },
            {
              id: 17,
              attributes: {
                name: "2H0A9972.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/large_2_H0_A9972_6c77378560.jpg",
                    hash: "large_2_H0_A9972_6c77378560",
                    mime: "image/jpeg",
                    name: "large_2H0A9972.jpeg",
                    path: null,
                    size: 45.82,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 45819,
                    provider_metadata: {
                      public_id: "Suits/large_2_H0_A9972_6c77378560",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/small_2_H0_A9972_6c77378560.jpg",
                    hash: "small_2_H0_A9972_6c77378560",
                    mime: "image/jpeg",
                    name: "small_2H0A9972.jpeg",
                    path: null,
                    size: 15.06,
                    width: 333,
                    height: 500,
                    sizeInBytes: 15058,
                    provider_metadata: {
                      public_id: "Suits/small_2_H0_A9972_6c77378560",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/medium_2_H0_A9972_6c77378560.jpg",
                    hash: "medium_2_H0_A9972_6c77378560",
                    mime: "image/jpeg",
                    name: "medium_2H0A9972.jpeg",
                    path: null,
                    size: 28.3,
                    width: 500,
                    height: 750,
                    sizeInBytes: 28297,
                    provider_metadata: {
                      public_id: "Suits/medium_2_H0_A9972_6c77378560",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/thumbnail_2_H0_A9972_6c77378560.jpg",
                    hash: "thumbnail_2_H0_A9972_6c77378560",
                    mime: "image/jpeg",
                    name: "thumbnail_2H0A9972.jpeg",
                    path: null,
                    size: 3.18,
                    width: 104,
                    height: 156,
                    sizeInBytes: 3178,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_2_H0_A9972_6c77378560",
                      resource_type: "image",
                    },
                  },
                },
                hash: "2_H0_A9972_6c77378560",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 431.38,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443581/Suits/2_H0_A9972_6c77378560.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/2_H0_A9972_6c77378560",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:26:22.260Z",
                updatedAt: "2024-09-27T13:26:22.260Z",
              },
            },
            {
              id: 8,
              attributes: {
                name: "casamento not2.jpeg",
                alternativeText: null,
                caption: null,
                width: 2000,
                height: 3000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/large_casamento_not2_ee8a546900.jpg",
                    hash: "large_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "large_casamento not2.jpeg",
                    path: null,
                    size: 35.59,
                    width: 667,
                    height: 1000,
                    sizeInBytes: 35592,
                    provider_metadata: {
                      public_id: "Suits/large_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/small_casamento_not2_ee8a546900.jpg",
                    hash: "small_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "small_casamento not2.jpeg",
                    path: null,
                    size: 12.46,
                    width: 333,
                    height: 500,
                    sizeInBytes: 12459,
                    provider_metadata: {
                      public_id: "Suits/small_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/medium_casamento_not2_ee8a546900.jpg",
                    hash: "medium_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "medium_casamento not2.jpeg",
                    path: null,
                    size: 22.58,
                    width: 500,
                    height: 750,
                    sizeInBytes: 22581,
                    provider_metadata: {
                      public_id: "Suits/medium_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443386/Suits/thumbnail_casamento_not2_ee8a546900.jpg",
                    hash: "thumbnail_casamento_not2_ee8a546900",
                    mime: "image/jpeg",
                    name: "thumbnail_casamento not2.jpeg",
                    path: null,
                    size: 2.69,
                    width: 104,
                    height: 156,
                    sizeInBytes: 2685,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_casamento_not2_ee8a546900",
                      resource_type: "image",
                    },
                  },
                },
                hash: "casamento_not2_ee8a546900",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 278.42,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443387/Suits/casamento_not2_ee8a546900.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/casamento_not2_ee8a546900",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:23:07.656Z",
                updatedAt: "2024-09-27T13:23:07.656Z",
              },
            },
          ],
        },
      },
      {
        id: 6,
        Titulo: "Coquetel",
        Descricao: [
          {
            type: "paragraph",
            children: [
              {
                text: "Coquetéis pedem um look elegante e descontraído. Um blazer, calça social e sapatos marrons garantem estilo e sofisticação.",
                type: "text",
              },
            ],
          },
        ],
        Fotos: {
          data: [
            {
              id: 18,
              attributes: {
                name: "2H0A0536.jpeg",
                alternativeText: null,
                caption: null,
                width: 3000,
                height: 2000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/large_2_H0_A0536_a91336b6d1.jpg",
                    hash: "large_2_H0_A0536_a91336b6d1",
                    mime: "image/jpeg",
                    name: "large_2H0A0536.jpeg",
                    path: null,
                    size: 119.72,
                    width: 1000,
                    height: 667,
                    sizeInBytes: 119718,
                    provider_metadata: {
                      public_id: "Suits/large_2_H0_A0536_a91336b6d1",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/small_2_H0_A0536_a91336b6d1.jpg",
                    hash: "small_2_H0_A0536_a91336b6d1",
                    mime: "image/jpeg",
                    name: "small_2H0A0536.jpeg",
                    path: null,
                    size: 36.42,
                    width: 500,
                    height: 333,
                    sizeInBytes: 36420,
                    provider_metadata: {
                      public_id: "Suits/small_2_H0_A0536_a91336b6d1",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/medium_2_H0_A0536_a91336b6d1.jpg",
                    hash: "medium_2_H0_A0536_a91336b6d1",
                    mime: "image/jpeg",
                    name: "medium_2H0A0536.jpeg",
                    path: null,
                    size: 73.02,
                    width: 750,
                    height: 500,
                    sizeInBytes: 73020,
                    provider_metadata: {
                      public_id: "Suits/medium_2_H0_A0536_a91336b6d1",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/thumbnail_2_H0_A0536_a91336b6d1.jpg",
                    hash: "thumbnail_2_H0_A0536_a91336b6d1",
                    mime: "image/jpeg",
                    name: "thumbnail_2H0A0536.jpeg",
                    path: null,
                    size: 10.51,
                    width: 234,
                    height: 156,
                    sizeInBytes: 10512,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_2_H0_A0536_a91336b6d1",
                      resource_type: "image",
                    },
                  },
                },
                hash: "2_H0_A0536_a91336b6d1",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 979.77,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/2_H0_A0536_a91336b6d1.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/2_H0_A0536_a91336b6d1",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:27:07.134Z",
                updatedAt: "2024-09-27T13:27:07.134Z",
              },
            },
            {
              id: 19,
              attributes: {
                name: "2H0A0530.jpeg",
                alternativeText: null,
                caption: null,
                width: 3000,
                height: 2000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/large_2_H0_A0530_7c72d47a85.jpg",
                    hash: "large_2_H0_A0530_7c72d47a85",
                    mime: "image/jpeg",
                    name: "large_2H0A0530.jpeg",
                    path: null,
                    size: 136.35,
                    width: 1000,
                    height: 667,
                    sizeInBytes: 136346,
                    provider_metadata: {
                      public_id: "Suits/large_2_H0_A0530_7c72d47a85",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443627/Suits/small_2_H0_A0530_7c72d47a85.jpg",
                    hash: "small_2_H0_A0530_7c72d47a85",
                    mime: "image/jpeg",
                    name: "small_2H0A0530.jpeg",
                    path: null,
                    size: 41.29,
                    width: 500,
                    height: 333,
                    sizeInBytes: 41290,
                    provider_metadata: {
                      public_id: "Suits/small_2_H0_A0530_7c72d47a85",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/medium_2_H0_A0530_7c72d47a85.jpg",
                    hash: "medium_2_H0_A0530_7c72d47a85",
                    mime: "image/jpeg",
                    name: "medium_2H0A0530.jpeg",
                    path: null,
                    size: 82.89,
                    width: 750,
                    height: 500,
                    sizeInBytes: 82889,
                    provider_metadata: {
                      public_id: "Suits/medium_2_H0_A0530_7c72d47a85",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/thumbnail_2_H0_A0530_7c72d47a85.jpg",
                    hash: "thumbnail_2_H0_A0530_7c72d47a85",
                    mime: "image/jpeg",
                    name: "thumbnail_2H0A0530.jpeg",
                    path: null,
                    size: 12.08,
                    width: 234,
                    height: 156,
                    sizeInBytes: 12079,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_2_H0_A0530_7c72d47a85",
                      resource_type: "image",
                    },
                  },
                },
                hash: "2_H0_A0530_7c72d47a85",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 1101.36,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443627/Suits/2_H0_A0530_7c72d47a85.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/2_H0_A0530_7c72d47a85",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:27:07.534Z",
                updatedAt: "2024-09-27T13:27:07.534Z",
              },
            },
            {
              id: 20,
              attributes: {
                name: "2H0A0667.jpeg",
                alternativeText: null,
                caption: null,
                width: 3000,
                height: 2000,
                formats: {
                  large: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443627/Suits/large_2_H0_A0667_4cf355e393.jpg",
                    hash: "large_2_H0_A0667_4cf355e393",
                    mime: "image/jpeg",
                    name: "large_2H0A0667.jpeg",
                    path: null,
                    size: 107,
                    width: 1000,
                    height: 667,
                    sizeInBytes: 106997,
                    provider_metadata: {
                      public_id: "Suits/large_2_H0_A0667_4cf355e393",
                      resource_type: "image",
                    },
                  },
                  small: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443627/Suits/small_2_H0_A0667_4cf355e393.jpg",
                    hash: "small_2_H0_A0667_4cf355e393",
                    mime: "image/jpeg",
                    name: "small_2H0A0667.jpeg",
                    path: null,
                    size: 28.46,
                    width: 500,
                    height: 333,
                    sizeInBytes: 28461,
                    provider_metadata: {
                      public_id: "Suits/small_2_H0_A0667_4cf355e393",
                      resource_type: "image",
                    },
                  },
                  medium: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443627/Suits/medium_2_H0_A0667_4cf355e393.jpg",
                    hash: "medium_2_H0_A0667_4cf355e393",
                    mime: "image/jpeg",
                    name: "medium_2H0A0667.jpeg",
                    path: null,
                    size: 60.04,
                    width: 750,
                    height: 500,
                    sizeInBytes: 60043,
                    provider_metadata: {
                      public_id: "Suits/medium_2_H0_A0667_4cf355e393",
                      resource_type: "image",
                    },
                  },
                  thumbnail: {
                    ext: ".jpeg",
                    url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443626/Suits/thumbnail_2_H0_A0667_4cf355e393.jpg",
                    hash: "thumbnail_2_H0_A0667_4cf355e393",
                    mime: "image/jpeg",
                    name: "thumbnail_2H0A0667.jpeg",
                    path: null,
                    size: 8.43,
                    width: 234,
                    height: 156,
                    sizeInBytes: 8429,
                    provider_metadata: {
                      public_id: "Suits/thumbnail_2_H0_A0667_4cf355e393",
                      resource_type: "image",
                    },
                  },
                },
                hash: "2_H0_A0667_4cf355e393",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 1286.32,
                url: "https://res.cloudinary.com/de5rrszh7/image/upload/v1727443627/Suits/2_H0_A0667_4cf355e393.jpg",
                previewUrl: null,
                provider: "cloudinary",
                provider_metadata: {
                  public_id: "Suits/2_H0_A0667_4cf355e393",
                  resource_type: "image",
                },
                createdAt: "2024-09-27T13:27:07.873Z",
                updatedAt: "2024-09-27T13:27:07.873Z",
              },
            },
          ],
        },
      },
    ],
  },
};
